name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: cppcheck-action
      uses: deep5050/cppcheck-action@v2.0.0
    - name: make
      run: make
    - name: make check
      run: make check
    - name: make distcheck
      run: make distcheck
